name: Build Dashboard

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check out GitHub Pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'out'

    - name: 'Generate Dashboard'
      uses: ethomson/issue-dashboard@v1.0.2
      with:
        config: |
          title: 'Dashboard'
          output:
            format: html
            filename: 'out/dashboard.html'
          sections:
          - title: 'Issues'
            widgets:
            - type: 'table'
              title: 'Open Issues'
              issue_query: 'repo:w3c/qtspecs is:open is:issue created:>2017-03-21 sort:created-asc'
            - type: 'table'
              title: 'Closed Issues (since last publication)'
              issue_query: 'repo:w3c/qtspecs is:closed is:issue created:>2017-03-21 sort:created-asc'
        token: ${{ github.token }}

    - name: Test
      run: |
        git add .
        git config user.name 'caribouW3'
        git config user.email 'carine@w3.org'
        git commit -m 'test' --allow-empty
        git push origin gh-pages
      working-directory: out
